### PR TITLE
Raise PHP verion in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
7.0 -> ~~7.1~~ ~~7.2~~ 7.4

as per https://github.com/johnbillion/extended-cpts/pull/125#issuecomment-655757973

### CODE REVIEW

**Review by johnbillion — APPROVED** [review]

**Comment by vinkla** [comment]
Since PHP 7.2 has already reached EOL we could probably jump to 7.3 instead?

https://www.php.net/supported-versions.php

**Comment by johnbillion** [comment]
I'm happy with 7.2, there's nothing in 7.3 specifically that I plan on using, and a lot of the sites I work on will still be on 7.2 for a while yet.

**Comment by johnbillion** [comment]
Changed my mind, we're going to 7.4.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
