### PR TITLE
Test wp 6.2 and PHP 8.2 in workflow

### PR DESCRIPTION
**Pull request by chrillep**
adds
* test for WP 6.2
* test for PHP 8.2
* fixes Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: `actions/checkout@v2`, `actions/cache@v1`, `shivammathur/setup-php@2.7.0`

### CODE REVIEW

**Comment by johnbillion** [comment]
Thanks. You can ignore the PHP test failures, they're due to an issue with WP-CLI 2.8.0 which should be fixed in the next point release.

**Comment by chrillep** [comment]
> Thanks. You can ignore the PHP test failures, they're due to an issue with WP-CLI 2.8.0 which should be fixed in the next point release.

Great! Wasn't sure why it was happening 😅 . 

sidenote:  why are the code sniffers only to run on PHP 7.4? Is it because backwards compat?

https://github.com/johnbillion/extended-cpts/blob/e50e32113136646e48968ec15ef860d166328729/.github/workflows/test.yml#L39-L40
https://github.com/johnbillion/extended-cpts/blob/e50e32113136646e48968ec15ef860d166328729/.github/workflows/test.yml#L74-L78
https://github.com/johnbillion/extended-cpts/blob/e50e32113136646e48968ec15ef860d166328729/composer.json#L48-L53

**Comment by chrillep** [comment]
@johnbillion ping :)

**Comment by johnbillion** [comment]
Thanks!

**Pull request merged**
