### PR TITLE
Fix args merge:

### PR DESCRIPTION
**Pull request by nlemoine**
- Fixes 'labels' and 'rewrite' merge in case 'public' is set to false

### CODE REVIEW

**Comment by nlemoine** [comment]
Sorry, I already have a PR pending in the develop branch.

**Comment by nlemoine** [comment]
Because `$this->defaults['rewrite]` can be set to `false` [here](https://github.com/johnbillion/extended-cpts/blob/d5d879aaf83e69c8a17a2c9e451f49abe8464e58/src/class-extended-cpt.php#L147)

**Comment by johnbillion** [comment]
Thanks for the PR! Can you provide some example code that demonstrates the problem please?

**Comment by nlemoine** [comment]
Sure. 
```php
register_extended_post_type('post_type', [
    'public' => false,
    'rewrite' => [
         'slug' => 'post-type',
    ]
]);
```

**Comment by nlemoine** [comment]
Hi @johnbillion 

I didn't get a notification for the "awaiting testing" label. I added a basic test. You check it without the PR, you'll see that errors are thrown. 

Let me know if some changes are requested.

**Comment by johnbillion** [comment]
Thanks, I'll see if I can find some time to pick this up

**Pull request merged**
