### PR TITLE
Remove composer patches and update taxonomy label tests for WP 5.9.0+

### LINKED ISSUE #197: wp-browser composer patch is no longer valid when running `composer install`
Hey John,

Running `composer install` results in:

```
  Applying patches for lucatume/wp-browser
    tests/patches/wp-browser-554.patch (https://github.com/lucatume/wp-browser/issues/554)
   Could not apply patch! Skipping. The error was: Cannot apply patch tests/patches/wp-browser-554.patch
```
As there's no composer.lock file, not sure which version you were patching but it's no longer valid and it does look like https://github.com/lucatume/wp-browser/issues/554 is fixed as of `3.0.22`.

In addition to this, if you use this library in another project with composer patching enabled, it fails because the [tests folder](https://github.com/johnbillion/extended-cpts/blob/5.0.1/.gitattributes#L5) is ignored on export, so the [patch](https://github.com/johnbillion/extended-cpts/blob/5.0.1/tests/patches/wp-browser-554.patch) doesn't exist to apply.

Any chance you're able to remove the patch or use a github .patch URL instead (if there's an upstream bug that still needs fixing) so it doesn't even need to exist in your repo?

Thanks!

### PR DESCRIPTION
**Pull request by defunctl**
- Fixes: https://github.com/johnbillion/extended-cpts/issues/197
- Adds WordPress 5.9 to the Github testing action.

### CODE REVIEW

**Comment by defunctl** [comment]
@johnbillion if you wouldn't mind allowing me to run workflows, I'd appreciate it :smile:

**Comment by johnbillion** [comment]
Thanks for the PR 👍

**Comment by defunctl** [comment]
@johnbillion would you like me to add WordPress 5.9 to your Github Workflow [tests matrix](https://github.com/johnbillion/extended-cpts/blob/5.0.1/.github/workflows/test.yml#L15-L21) in this PR?

**Comment by johnbillion** [comment]
Please!

**Comment by defunctl** [comment]
@johnbillion done :smiley: need workflow approval again, please.

**Pull request merged**
