### PR TITLE
option to disable block editor

### PR DESCRIPTION
**Pull request by carmoreira**
I find it very useful for my projects to be able to disable Gutenberg on specific CPTs, since they don't use an editor. 
It would be enabled by default and disabled on request, with an admin parameter. 
I can update the docs, if it's approved.

### CODE REVIEW

**Comment by johnbillion** [comment]
Thanks for the PR! I wonder if this should take into account the Classic Editor plugin as respect that as a default? Then allow an explicit `true`/`false` in this parameter?

**Comment by johnbillion** [comment]
Maybe with `null` as the default, which means do nothing, then `true` to force enable the block editor and `false` to force disable it.

**Comment by carmoreira** [comment]
@johnbillion yes, good idea. We could hook into the filter after the Classic Editor plugin to be able to force a true/false and workaround their settings. 
I have updated the code and tested it with current version of Classic Editor (v1.5) and it seems to work well.

**Comment by vinkla** [comment]
Might not be as clear but doesn't the `show_in_rest` option already have this behaviour? Setting `show_in_rest` to `false` makes WordPress disable Gutenberg.

**Comment by carmoreira** [comment]
You're right @vinkla but I think there might be cases where we want the cpt to be available in the REST-API but don't want to use the code editor. This would just help in those scenarios.

**Comment by vinkla** [comment]
>..I think there might be cases where we want the cpt to be available in the REST-API but don't want to use the code editor.

I agree, that makes sense.

**Pull request merged**
