### PR TITLE
Support date_format within admin_filters

### PR DESCRIPTION
**Pull request by lipemat**
Super basic implementation of supporting date_format within admin filters. 
Used when you have a timestamp stored as your meta value and you want a date displayed in the dropdown.

### CODE REVIEW

**Comment by ajuliano** [comment]
I also want this feature, is there a way to get it to work?

**Comment by lipemat** [comment]
You may use the forked version which includes this functionality https://github.com/lipemat/extended-cpts

**Comment by ajuliano** [comment]
Alright. I tested the solution, but if I have multiple posts (cpt's) in a given month the dropdown will show multiple entries for one month if I use the date format M Y for example. Do you have a solution for that?

Thanks!

**Comment by johnbillion** [comment]
I've been thinking about this and due to @ajuliano's comment I'm going to close this as wontfix. I think a better approach would be to use a callback function for the `options` argument of the filter, and return an array your properly formatted list of options there.

Thanks anyway!

**Pull request closed without merging**
