### PR TITLE
Update composer file

### PR DESCRIPTION
**Pull request by vinkla**
I've updated and formatted the `composer.json` file. Also updated the packages constraints.

### CODE REVIEW

**Comment by johnbillion** [comment]
The test suite isn't compatible with PHPUnit 6 just yet.

**Comment by vinkla** [comment]
Oh, I see. Let close this for now.

**Comment by vinkla** [comment]
I've updated the PHPUnit version.

**Comment by johnbillion** [comment]
Thanks. Do you have a link to some documentation about preferring the caret `^` over the tilde `~`?

**Comment by vinkla** [comment]
Here you go; [Caret Version Range](https://getcomposer.org/doc/articles/versions.md#caret-version-range-).

**Comment by vinkla** [comment]
You definitely want the `^` for the PHP version since `>=` means we support PHP 8.0. We don't know if this package works with 8.0 just yet.

**Comment by johnbillion** [comment]
The indentation in this file seems to have gone weird. It's using three spaces for indentation.

**Comment by vinkla** [comment]
I've fixed the indentation and added a `.editorconfig` file.

**Comment by vinkla** [comment]
@johnbillion I've fixed the conflicts.

**Comment by vinkla** [comment]
Any update on this pull request.

**Comment by johnbillion** [comment]
Cheers @vinkla, I'll get this in to the next version.

**Comment by vinkla** [comment]
@johnbillion great!

**Comment by vinkla** [comment]
@johnbillion make you could merge this and then take a look at it before releasing the next version? 

This pull request basically just updates the syntax.

**Pull request merged**
