### PR TITLE
Introduce static analysis

### PR DESCRIPTION
**Pull request by szepeviktor**
@johnbillion and fix errors!

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should we add it to Travis CI with PHP 7.3?

**Comment by johnbillion** [comment]
Thanks for the pull request. I've looked into PHPStan in the past with WordPress but it seems to depend on `giacocorsiglia/wordpress-stubs` which isn't very well maintained.

Is there a way to skip relying on `giacocorsiglia/wordpress-stubs` and allow PHPStan to run from a specified directory that contains WordPress? (ie. via `roots/wordpress`).

**Comment by johnbillion** [comment]
`giacocorsiglia/wordpress-stubs` also doesn't currently work with PHP 7.3 as you already know.

**Comment by szepeviktor** [comment]
The problem is that WP core has side-effects which will be **executed** as will surely fail.
So we need stubs. I starting a stub library https://github.com/php-stubs Its first repo will be WordPress.

**Comment by szepeviktor** [comment]
> `giacocorsiglia/wordpress-stubs` also doesn't currently work with PHP 7.3 as you already know.

My stubs will exclude any "compat" code found in core.

**Comment by johnbillion** [comment]
Keep me posted! My main concern is keeping the stubs library up to date with new releases of WordPress.

**Comment by szepeviktor** [comment]
I create big red button 🔴 to add the next release. I've pushed all my clients to use phpstan, so I daily see it in CI.

**Comment by szepeviktor** [comment]
@johnbillion After months of trouble with WordPress stubs I've released https://github.com/php-stubs/wordpress-stubs And my [phpstan package depends on it](https://github.com/szepeviktor/phpstan-wordpress/blob/master/composer.json#L15).

**Comment by johnbillion** [comment]
@szepeviktor What needs doing here to finish this off?

* I see a @TODO in the config file
* Can you add the required composer.json change?
* Anything else?

**Comment by szepeviktor** [comment]
@johnbillion Basically PHPStan and my extension got more clever :)
So we need to run it again.

Regarding the TODO: above Level 5 there is more work to do an of course more benefits!

Sending the final commit...

**Comment by szepeviktor** [comment]
```json
	"require": {
		"php": "^7.0"
	}
```

Ooops! PHPStan is a modern tool, won't run on PHP 7.0.
May I add it to CI with `composer require`?

**Comment by johnbillion** [comment]
To be honest I could bump ExtCPTs to PHP 7.1. Let's do that.

**Comment by szepeviktor** [comment]
Done 🍏

**Pull request merged**
